export enum WaasPolicyAction {
  CREATE_WALLET = 'CREATE_WALLET',
  SIGN_TRANSACTION = 'SIGN_TRANSACTION',
  CREATE_USER = 'CREATE_USER',
  DELETE_USER = 'DELETE_USER',
  DELETE_ORGANIZATION = 'DELETE_ORGANIZATION',
  UPDATE_POLICY = 'UPDATE_POLICY',
  ADD_POLICY = 'ADD_POLICY',
  REMOVE_POLICY = 'REMOVE_POLICY',
}
